### ISSUE TITLE
Running on ubuntu

### ISSUE THREAD

**Issue by nickjohnsonm** [jsinghsamuel/Dashing-Nagiosxi#1]
I have working dashing installation.  Gemfile:

```
source 'https://rubygems.org'

gem 'dashing'
gem 'open-uri'
gem 'nokogiri'

## Remove this if you don't need a twitter widget.
#gem 'twitter', '>= 5.9.0'

```

Bundle has this output:

```
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Could not find gem 'open-uri (>= 0) ruby' in the gems available on this machine.

Looks like this require is in the job rb files, I took out this require and when running get a scheduler error:

================================================================================
scheduler caught exception:
undefined local variable or method `content' for main:Object
/root/project/jobs/nagiosxi.rb:55:in `block in <top (required)>'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `call'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `trigger_block'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:204:in `block in trigger'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `call'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `block in trigger_job'
================================================================================

```

Anything I should look at?

**Comment by nickjohnsonm** [comment]
Looks like just had to run this

```
apt-get install zlib1g-dev
```
